"""新增使用者頭像圖片路徑欄位

Revision ID: 1de1756e55a0
Revises: 22edc96922e8
Create Date: 2025-01-24 10:51:10.817722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1de1756e55a0'
down_revision: Union[str, None] = '22edc96922e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('headshot_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'headshot_path')
    # ### end Alembic commands ###
