"""20250519 Update

Revision ID: 6d71992d0740
Revises: 7dae6e1967a7
Create Date: 2025-05-19 11:37:56.681074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d71992d0740'
down_revision: Union[str, None] = '7dae6e1967a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.drop_column('tasks', 'is_done')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
