"""Add Field 'is_done' to Task Model

Revision ID: 7f1fba277cae
Revises: 1de1756e55a0
Create Date: 2025-02-05 10:29:01.235111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f1fba277cae'
down_revision: Union[str, None] = '1de1756e55a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_done', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_done')
    # ### end Alembic commands ###
