"""Add missing cols to Tag, and add is_superuser to User

Revision ID: 86ccf834bbe1
Revises: e2988e115d2b
Create Date: 2024-12-17 14:39:14.251531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86ccf834bbe1'
down_revision: Union[str, None] = 'e2988e115d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tags', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'tags', ['name'])
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('tags', 'is_public')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
