"""Alter Field 'role_id' default = Role.USER to User model.

Revision ID: cf63bb4da1d2
Revises: 7f1fba277cae
Create Date: 2025-02-05 11:04:15.498976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf63bb4da1d2'
down_revision: Union[str, None] = '7f1fba277cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
